### ISSUE TITLE
name of this repository

### ISSUE THREAD

**Issue by vincentvanhees** [research-software-directory/frontend#2]
There are two repositories within the NLeSC GitHub organisation called 'rsd....' and one called 'research-software-directory....'. It would be easier if naming could be kept consistent, even if it is 'just' for internal communication. So, if you could rename this repository that would be good.

**Comment by Tommos0** [comment]
We currently have
- research-software-directory-backend
- research-software-directory-admin
- research-software-directory-frontend
- rsd-instruction

It's probably easier to rename rsd-instruction, but I'm afraid a lot of us are using this link, so I'd rather not do it right now

**Comment by jspaaks** [comment]
While we're at it, maybe we should make a research-software-directory organization, with
- admin
- backend
- frontend
- instruction
- management

Prolly a little bit easier to disseminate when that time comes

**Comment by sverhoeven** [comment]
Could you add the https://github.com/research-software-directory organization to https://github.com/NLeSC/nlesc.github.io?

**Comment by jspaaks** [comment]
what stefan says

**Comment by jspaaks** [comment]
Done

**Comment by sverhoeven** [comment]
Thanks
