### ISSUE TITLE
citeas citation not quite what it needs to be

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/frontend#21]
(on behalf of @cwmeijer)

could simply be a data problem, but for what it's worth:

Als ik op 'cite this software' klik bij mcfly en dan APA kies dan krijg ik de volgende tekst in een bestandje:
"
Center, N..  (2016). mcfly. GitHub repository. Retrieved from https://github.com/NLeSC/mcfly
"
Dat lijkt me niet het juiste formaat voor een citatie, toch?

**Comment by Tommos0** [comment]
I'm using `citeas`, data output here: `http://api.citeas.org/product/https://github.com/NLeSC/mcfly`.
mcFly seems to have a Zenodo DOI, but citeas can't seem to find it. Perhaps adding a citation file to the github repo could help?

**Comment by jspaaks** [comment]
About detecting DOIs by citeas: it can come from the readme as well, citeas takes a brute-force approach, just checking various places where information may be found.

I actually prefer the explicit way of CFF over just randomly formatted CITATION files and other sources. Unfortunately, citeas doesn't do CFF formatted CITATION files yet. In the meantime, I made [this](https://github.com/jspaaks/citationcff): github repo url in, bibtex (and maybe later, others) out. Obviously, it doesn't implement all of the CFF spec yet. Would it be possible/useful to combine this with citeas do you think?

**Comment by Tommos0** [comment]
#42
