### ISSUE TITLE
Search Engine Optimization: add structured data for software

### ISSUE THREAD

**Issue by Tommos0** [research-software-directory/frontend#44]
see https://developers.google.com/search/docs/guides/intro-structured-data

**Comment by jspaaks** [comment]
we might be able to generate the structured data from the CITATION.cff using the mapping from CodeMeta https://github.com/codemeta/codemeta/blob/master/crosswalk.csv

**Comment by jspaaks** [comment]
There's also a thing called Breadcrumbs which helps define the site hierarchy https://developers.google.com/search/docs/data-types/breadcrumb

**Comment by jspaaks** [comment]
list of tools: https://developers.google.com/search/tools/

**Comment by jspaaks** [comment]
maybe something like this:
```javascript
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "item": {
      "@id": "https://research-software.nl",
      "name": "Research Software Directory"
    }
  },{
    "@type": "ListItem",
    "position": 2,
    "item": {
      "@id": "https://research-software.nl/software",
      "name": "Software"
    }
  },{
    "@type": "ListItem",
    "position": 3,
    "item": {
      "@id": "https://research-software.nl/software/mcfly",
      "name": "mcfly"
    }
  }]
}
</script>
```

**Comment by jspaaks** [comment]
We now include breadcrumbs, and can generate structured data according to codemeta using https://github.com/citation-file-format/cff-converter-python 's ``as_codemeta()``function. Closing this issue.
