### ISSUE TITLE
Tool page: Projects with... testimonial by

### ISSUE THREAD

**Issue by silo-sietse** [research-software-directory/frontend#55]
Dummy organisation needs to be replaced by actual organisation if there is one to be mentioned.
Why is there a Url in this string? Should the entire Testimonial be a link to this Url?

Example Tool with testimonial: https://www.research-software.nl/software/twiqs.nl

**Comment by jspaaks** [comment]
Hi Sietse, I've removed the link (was entered as data). We don;t need to link to anywhere from the testimonial AFAIC. 

The Dummy Organization still needs to go though.
